// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.WebControls;

namespace Connect.Modules.UserManagement.AccountManagement
{
    public partial class Reports
    {

        /// <summary>
        /// rptReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Repeater rptReports;

        /// <summary>
        /// cmdNewReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdNewReport;

        protected LinkButton cmdNewReport
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdNewReport;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdNewReport != null)
                {
                    _cmdNewReport.Click -= cmdNewReport_Click;
                }

                _cmdNewReport = value;
                if (_cmdNewReport != null)
                {
                    _cmdNewReport.Click += cmdNewReport_Click;
                }
            }
        }

        /// <summary>
        /// cmdBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdBack;

        protected LinkButton cmdBack
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdBack;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdBack != null)
                {
                    _cmdBack.Click -= cmdBack_Click;
                }

                _cmdBack = value;
                if (_cmdBack != null)
                {
                    _cmdBack.Click += cmdBack_Click;
                }
            }
        }

        /// <summary>
        /// pnlReportForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlReportForm;

        /// <summary>
        /// plReportName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl plReportName;

        /// <summary>
        /// txtReportName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtReportName;

        /// <summary>
        /// plReportSql control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl plReportSql;

        /// <summary>
        /// txtReportSql control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtReportSql;

        /// <summary>
        /// cmdAddReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdAddReport;

        protected LinkButton cmdAddReport
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdAddReport;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdAddReport != null)
                {
                    _cmdAddReport.Click -= cmdAddReport_Click;
                }

                _cmdAddReport = value;
                if (_cmdAddReport != null)
                {
                    _cmdAddReport.Click += cmdAddReport_Click;
                }
            }
        }

        /// <summary>
        /// cmdUpdateReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdUpdateReport;

        protected LinkButton cmdUpdateReport
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdUpdateReport;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdUpdateReport != null)
                {
                    _cmdUpdateReport.Click -= cmdUpdateReport_Click;
                }

                _cmdUpdateReport = value;
                if (_cmdUpdateReport != null)
                {
                    _cmdUpdateReport.Click += cmdUpdateReport_Click;
                }
            }
        }

        /// <summary>
        /// cmdDeleteReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdDeleteReport;

        protected LinkButton cmdDeleteReport
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdDeleteReport;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdDeleteReport != null)
                {
                    _cmdDeleteReport.Click -= cmdDeleteReport_Click;
                }

                _cmdDeleteReport = value;
                if (_cmdDeleteReport != null)
                {
                    _cmdDeleteReport.Click += cmdDeleteReport_Click;
                }
            }
        }

        /// <summary>
        /// cmdCancelReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdCancelReport;

        protected LinkButton cmdCancelReport
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdCancelReport;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdCancelReport != null)
                {
                    _cmdCancelReport.Click -= cmdCancelReport_Click;
                }

                _cmdCancelReport = value;
                if (_cmdCancelReport != null)
                {
                    _cmdCancelReport.Click += cmdCancelReport_Click;
                }
            }
        }
    }
}