// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace Connect.Modules.UserManagement.AccountManagement
{
    public partial class Settings
    {

        /// <summary>
        /// lblAllowReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAllowReports;

        /// <summary>
        /// chkAllowReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkAllowReports;

        /// <summary>
        /// lblAllowCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAllowCreate;

        /// <summary>
        /// chkAllowCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkAllowCreate;

        /// <summary>
        /// lblAllowDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAllowDelete;

        /// <summary>
        /// chkAllowDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkAllowDelete;

        /// <summary>
        /// lblAllowHardDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAllowHardDelete;

        /// <summary>
        /// chkAllowHardDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkAllowHardDelete;

        /// <summary>
        /// lblAllowExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAllowExport;

        /// <summary>
        /// chkAllowExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox _chkAllowExport;

        protected CheckBox chkAllowExport
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkAllowExport;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkAllowExport != null)
                {
                    _chkAllowExport.CheckedChanged -= chkAllowExport_CheckedChanged;
                }

                _chkAllowExport = value;
                if (_chkAllowExport != null)
                {
                    _chkAllowExport.CheckedChanged += chkAllowExport_CheckedChanged;
                }
            }
        }

        /// <summary>
        /// dvExportFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl dvExportFields;

        /// <summary>
        /// lblExportFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblExportFields;

        /// <summary>
        /// txtExportFields control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtExportFields;

        /// <summary>
        /// lblAllowSendMessages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAllowSendMessages;

        /// <summary>
        /// chkAllowSendMessages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBox chkAllowSendMessages;

        /// <summary>
        /// lblAllowedRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAllowedRoles;

        /// <summary>
        /// chkAllowedRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBoxList _chkAllowedRoles;

        protected CheckBoxList chkAllowedRoles
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkAllowedRoles;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkAllowedRoles != null)
                {
                    _chkAllowedRoles.SelectedIndexChanged -= chkAllowedRoles_SelectedIndexChanged;
                }

                _chkAllowedRoles = value;
                if (_chkAllowedRoles != null)
                {
                    _chkAllowedRoles.SelectedIndexChanged += chkAllowedRoles_SelectedIndexChanged;
                }
            }
        }

        /// <summary>
        /// lblPreselectRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblPreselectRole;

        /// <summary>
        /// drpPreselectRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpPreselectRole;

        /// <summary>
        /// lblUserTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblUserTabs;

        /// <summary>
        /// chkUserTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBoxList chkUserTabs;

        /// <summary>
        /// lblAdditionalControls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.UI.UserControls.LabelControl lblAdditionalControls;

        /// <summary>
        /// txtAditionalControls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtAditionalControls;
    }
}