// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace Connect.Modules.UserManagement.AccountManagement
{
    public partial class View
    {

        /// <summary>
        /// pnlError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlError;

        /// <summary>
        /// lblError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblError;

        /// <summary>
        /// pnlSuccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlSuccess;

        /// <summary>
        /// lblSucess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblSucess;

        /// <summary>
        /// pnlCreateAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlCreateAccount;

        /// <summary>
        /// cmdCreateAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdCreateAccount;

        protected LinkButton cmdCreateAccount
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdCreateAccount;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdCreateAccount != null)
                {
                    _cmdCreateAccount.Click -= cmdCreateAccount_Click;
                }

                _cmdCreateAccount = value;
                if (_cmdCreateAccount != null)
                {
                    _cmdCreateAccount.Click += cmdCreateAccount_Click;
                }
            }
        }

        /// <summary>
        /// pnlBackToList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlBackToList;

        /// <summary>
        /// cmdBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdBack;

        protected LinkButton cmdBack
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdBack;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdBack != null)
                {
                    _cmdBack.Click -= cmdBack_Click;
                }

                _cmdBack = value;
                if (_cmdBack != null)
                {
                    _cmdBack.Click += cmdBack_Click;
                }
            }
        }

        /// <summary>
        /// pnlSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlSearch;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtSearch;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _btnSearch;

        protected LinkButton btnSearch
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnSearch;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnSearch != null)
                {
                    _btnSearch.Click -= btnSearch_Click;
                }

                _btnSearch = value;
                if (_btnSearch != null)
                {
                    _btnSearch.Click += btnSearch_Click;
                }
            }
        }

        /// <summary>
        /// ctlRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnTreeView ctlRoles;

        /// <summary>
        /// pnlHardDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlHardDelete;

        /// <summary>
        /// btnHardDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _btnHardDelete;

        protected LinkButton btnHardDelete
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnHardDelete;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnHardDelete != null)
                {
                    _btnHardDelete.Click -= btnHardDelete_Click;
                }

                _btnHardDelete = value;
                if (_btnHardDelete != null)
                {
                    _btnHardDelete.Click += btnHardDelete_Click;
                }
            }
        }

        /// <summary>
        /// pnlExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlExport;

        /// <summary>
        /// btnExport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _btnExport;

        protected LinkButton btnExport
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnExport;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnExport != null)
                {
                    _btnExport.Click -= btnExport_Click;
                }

                _btnExport = value;
                if (_btnExport != null)
                {
                    _btnExport.Click += btnExport_Click;
                }
            }
        }

        /// <summary>
        /// pnlMessageUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlMessageUsers;

        /// <summary>
        /// btnMessageUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HyperLink btnMessageUsers;

        /// <summary>
        /// pnlReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlReport;

        /// <summary>
        /// drpReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpReports;

        /// <summary>
        /// btnReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _btnReport;

        protected LinkButton btnReport
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnReport;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnReport != null)
                {
                    _btnReport.Click -= btnReport_Click;
                }

                _btnReport = value;
                if (_btnReport != null)
                {
                    _btnReport.Click += btnReport_Click;
                }
            }
        }

        /// <summary>
        /// pnlGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlGrid;

        /// <summary>
        /// UserGridTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl UserGridTabs;

        /// <summary>
        /// lblGridTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblGridTab;

        /// <summary>
        /// lblPreferencesTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblPreferencesTab;

        /// <summary>
        /// grdUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnGrid _grdUsers;

        protected DotNetNuke.Web.UI.WebControls.DnnGrid grdUsers
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _grdUsers;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_grdUsers != null)
                {
                    _grdUsers.PreRender -= grdUsers_PreRender;
                    _grdUsers.NeedDataSource -= grdUsers_NeedDataSource;
                    _grdUsers.ItemDataBound -= grdUsers_ItemDataBound;
                }

                _grdUsers = value;
                if (_grdUsers != null)
                {
                    _grdUsers.PreRender += grdUsers_PreRender;
                    _grdUsers.NeedDataSource += grdUsers_NeedDataSource;
                    _grdUsers.ItemDataBound += grdUsers_ItemDataBound;
                }
            }
        }

        /// <summary>
        /// cmdBulkDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdBulkDelete;

        protected LinkButton cmdBulkDelete
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdBulkDelete;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdBulkDelete != null)
                {
                    _cmdBulkDelete.Click -= cmdBulkDelete_Click;
                }

                _cmdBulkDelete = value;
                if (_cmdBulkDelete != null)
                {
                    _cmdBulkDelete.Click += cmdBulkDelete_Click;
                }
            }
        }

        /// <summary>
        /// cmdBulkRemove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdBulkRemove;

        protected LinkButton cmdBulkRemove
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdBulkRemove;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdBulkRemove != null)
                {
                    _cmdBulkRemove.Click -= cmdBulkRemove_Click;
                }

                _cmdBulkRemove = value;
                if (_cmdBulkRemove != null)
                {
                    _cmdBulkRemove.Click += cmdBulkRemove_Click;
                }
            }
        }

        /// <summary>
        /// cmdHardDeleteSelected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdHardDeleteSelected;

        protected LinkButton cmdHardDeleteSelected
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdHardDeleteSelected;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdHardDeleteSelected != null)
                {
                    _cmdHardDeleteSelected.Click -= cmdHardDeleteSelected_Click;
                }

                _cmdHardDeleteSelected = value;
                if (_cmdHardDeleteSelected != null)
                {
                    _cmdHardDeleteSelected.Click += cmdHardDeleteSelected_Click;
                }
            }
        }

        /// <summary>
        /// lblSearchOptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblSearchOptions;

        /// <summary>
        /// chkSearchCols control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBoxList chkSearchCols;

        /// <summary>
        /// lblGridSetup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblGridSetup;

        /// <summary>
        /// chkGridOptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBoxList chkGridOptions;

        /// <summary>
        /// lblPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblPageSize;

        /// <summary>
        /// drpPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DropDownList drpPageSize;

        /// <summary>
        /// btnApplyOptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _btnApplyOptions;

        protected LinkButton btnApplyOptions
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnApplyOptions;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnApplyOptions != null)
                {
                    _btnApplyOptions.Click -= btnApplyOptions_Click;
                }

                _btnApplyOptions = value;
                if (_btnApplyOptions != null)
                {
                    _btnApplyOptions.Click += btnApplyOptions_Click;
                }
            }
        }

        /// <summary>
        /// pnlUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlUser;

        /// <summary>
        /// UserDetailTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl UserDetailTabs;

        /// <summary>
        /// tabAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl tabAccount;

        /// <summary>
        /// lblAccountTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblAccountTab;

        /// <summary>
        /// tabPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl tabPassword;

        /// <summary>
        /// lblPasswordTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblPasswordTab;

        /// <summary>
        /// tabProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl tabProfile;

        /// <summary>
        /// lblProfileTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblProfileTab;

        /// <summary>
        /// tabRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl tabRoles;

        /// <summary>
        /// lblRolesTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblRolesTab;

        /// <summary>
        /// tabEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl tabEmail;

        /// <summary>
        /// lblEmailTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblEmailTab;

        /// <summary>
        /// tabMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl tabMessage;

        /// <summary>
        /// lblMessageTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblMessageTab;

        /// <summary>
        /// tabSites control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private HtmlGenericControl tabSites;

        /// <summary>
        /// lblSitesTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblSitesTab;

        /// <summary>
        /// plhAdditionalTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private PlaceHolder plhAdditionalTabs;

        /// <summary>
        /// pnlAccountTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlAccountTab;

        /// <summary>
        /// lblAccountNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblAccountNote;

        /// <summary>
        /// plhUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private PlaceHolder plhUser;

        /// <summary>
        /// lblMemberSinceLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblMemberSinceLabel;

        /// <summary>
        /// lblMemberSince control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblMemberSince;

        /// <summary>
        /// lblLastLoginLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblLastLoginLabel;

        /// <summary>
        /// lblLastLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblLastLogin;

        /// <summary>
        /// lblLastActivityLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblLastActivityLabel;

        /// <summary>
        /// lblLastActivity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblLastActivity;

        /// <summary>
        /// lblLastPasswordChangeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblLastPasswordChangeLabel;

        /// <summary>
        /// lblLastPasswordChange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblLastPasswordChange;

        /// <summary>
        /// lblLastLockoutLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblLastLockoutLabel;

        /// <summary>
        /// lblLastLockout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblLastLockout;

        /// <summary>
        /// lblUserOnlineStatusLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblUserOnlineStatusLabel;

        /// <summary>
        /// lblUserOnlineStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblUserOnlineStatus;

        /// <summary>
        /// lblAuthorizedStatusLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblAuthorizedStatusLabel;

        /// <summary>
        /// lblAuthorizedStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblAuthorizedStatus;

        /// <summary>
        /// lblLockoutStatusLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblLockoutStatusLabel;

        /// <summary>
        /// lblLockoutStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblLockoutStatus;

        /// <summary>
        /// lblForcePasswordChangeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblForcePasswordChangeLabel;

        /// <summary>
        /// lblForcePasswordChange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblForcePasswordChange;

        /// <summary>
        /// cmdUpdateAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdUpdateAccount;

        protected LinkButton cmdUpdateAccount
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdUpdateAccount;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdUpdateAccount != null)
                {
                    _cmdUpdateAccount.Click -= cmdUpdateAccount_Click;
                }

                _cmdUpdateAccount = value;
                if (_cmdUpdateAccount != null)
                {
                    _cmdUpdateAccount.Click += cmdUpdateAccount_Click;
                }
            }
        }

        /// <summary>
        /// cmdUnlockAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdUnlockAccount;

        protected LinkButton cmdUnlockAccount
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdUnlockAccount;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdUnlockAccount != null)
                {
                    _cmdUnlockAccount.Click -= cmdUnlockAccount_Click;
                }

                _cmdUnlockAccount = value;
                if (_cmdUnlockAccount != null)
                {
                    _cmdUnlockAccount.Click += cmdUnlockAccount_Click;
                }
            }
        }

        /// <summary>
        /// cmdAuthorizeAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdAuthorizeAccount;

        protected LinkButton cmdAuthorizeAccount
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdAuthorizeAccount;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdAuthorizeAccount != null)
                {
                    _cmdAuthorizeAccount.Click -= cmdAuthorizeAccount_Click;
                }

                _cmdAuthorizeAccount = value;
                if (_cmdAuthorizeAccount != null)
                {
                    _cmdAuthorizeAccount.Click += cmdAuthorizeAccount_Click;
                }
            }
        }

        /// <summary>
        /// cmdForcePasswordChange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdForcePasswordChange;

        protected LinkButton cmdForcePasswordChange
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdForcePasswordChange;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdForcePasswordChange != null)
                {
                    _cmdForcePasswordChange.Click -= cmdForcePasswordChange_Click;
                }

                _cmdForcePasswordChange = value;
                if (_cmdForcePasswordChange != null)
                {
                    _cmdForcePasswordChange.Click += cmdForcePasswordChange_Click;
                }
            }
        }

        /// <summary>
        /// cmdDeleteAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdDeleteAccount;

        protected LinkButton cmdDeleteAccount
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdDeleteAccount;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdDeleteAccount != null)
                {
                    _cmdDeleteAccount.Click -= cmdDeleteAccount_Click;
                }

                _cmdDeleteAccount = value;
                if (_cmdDeleteAccount != null)
                {
                    _cmdDeleteAccount.Click += cmdDeleteAccount_Click;
                }
            }
        }

        /// <summary>
        /// cmdRestoreAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdRestoreAccount;

        protected LinkButton cmdRestoreAccount
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdRestoreAccount;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdRestoreAccount != null)
                {
                    _cmdRestoreAccount.Click -= cmdRestoreAccount_Click;
                }

                _cmdRestoreAccount = value;
                if (_cmdRestoreAccount != null)
                {
                    _cmdRestoreAccount.Click += cmdRestoreAccount_Click;
                }
            }
        }

        /// <summary>
        /// pnlPasswordTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlPasswordTab;

        /// <summary>
        /// lblPasswordNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblPasswordNote;

        /// <summary>
        /// pnlResetButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlResetButton;

        /// <summary>
        /// cmdResetPasswordLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdResetPasswordLink;

        protected LinkButton cmdResetPasswordLink
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdResetPasswordLink;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdResetPasswordLink != null)
                {
                    _cmdResetPasswordLink.Click -= cmdResetPasswordLink_Click;
                }

                _cmdResetPasswordLink = value;
                if (_cmdResetPasswordLink != null)
                {
                    _cmdResetPasswordLink.Click += cmdResetPasswordLink_Click;
                }
            }
        }

        /// <summary>
        /// pnlPassword_Step1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlPassword_Step1;

        /// <summary>
        /// lblPassword1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private UserControl lblPassword1;

        /// <summary>
        /// txtPassword1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtPassword1;

        /// <summary>
        /// lblPassword2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private UserControl lblPassword2;

        /// <summary>
        /// txtPassword2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtPassword2;

        /// <summary>
        /// cmdUpdatePassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdUpdatePassword;

        protected LinkButton cmdUpdatePassword
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdUpdatePassword;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdUpdatePassword != null)
                {
                    _cmdUpdatePassword.Click -= cmdUpdatePassword_Click;
                }

                _cmdUpdatePassword = value;
                if (_cmdUpdatePassword != null)
                {
                    _cmdUpdatePassword.Click += cmdUpdatePassword_Click;
                }
            }
        }

        /// <summary>
        /// pnlPassword_Step2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlPassword_Step2;

        /// <summary>
        /// txtNotifyPasswordSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnTextBox txtNotifyPasswordSubject;

        /// <summary>
        /// txtNotifyPasswordBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnEditor txtNotifyPasswordBody;

        /// <summary>
        /// btnNotifyPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnNotifyPassword;

        protected Button btnNotifyPassword
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnNotifyPassword;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnNotifyPassword != null)
                {
                    _btnNotifyPassword.Click -= btnNotifyPassword_Click;
                }

                _btnNotifyPassword = value;
                if (_btnNotifyPassword != null)
                {
                    _btnNotifyPassword.Click += btnNotifyPassword_Click;
                }
            }
        }

        /// <summary>
        /// btnNotifyPasswordSkip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnNotifyPasswordSkip;

        protected Button btnNotifyPasswordSkip
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnNotifyPasswordSkip;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnNotifyPasswordSkip != null)
                {
                    _btnNotifyPasswordSkip.Click -= btnNotifyPasswordSkip_Click;
                }

                _btnNotifyPasswordSkip = value;
                if (_btnNotifyPasswordSkip != null)
                {
                    _btnNotifyPasswordSkip.Click += btnNotifyPasswordSkip_Click;
                }
            }
        }

        /// <summary>
        /// pnlProfileTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlProfileTab;

        /// <summary>
        /// lblProfileNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblProfileNote;

        /// <summary>
        /// plhProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private PlaceHolder plhProfile;

        /// <summary>
        /// cmdUpdateProfile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdUpdateProfile;

        protected LinkButton cmdUpdateProfile
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdUpdateProfile;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdUpdateProfile != null)
                {
                    _cmdUpdateProfile.Click -= cmdUpdateProfile_Click;
                }

                _cmdUpdateProfile = value;
                if (_cmdUpdateProfile != null)
                {
                    _cmdUpdateProfile.Click += cmdUpdateProfile_Click;
                }
            }
        }

        /// <summary>
        /// pnlRolesTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlRolesTab;

        /// <summary>
        /// lblRolesNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblRolesNote;

        /// <summary>
        /// pnlRoleChange_Step1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlRoleChange_Step1;

        /// <summary>
        /// drpRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnComboBox drpRoles;

        /// <summary>
        /// ctlRoleDatFrom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnDatePicker ctlRoleDatFrom;

        /// <summary>
        /// ctlRoleDateTo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnDatePicker ctlRoleDateTo;

        /// <summary>
        /// btnAddToRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnAddToRole;

        protected Button btnAddToRole
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnAddToRole;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnAddToRole != null)
                {
                    _btnAddToRole.Click -= btnAddToRole_Click;
                }

                _btnAddToRole = value;
                if (_btnAddToRole != null)
                {
                    _btnAddToRole.Click += btnAddToRole_Click;
                }
            }
        }

        /// <summary>
        /// grdUserRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnGrid _grdUserRoles;

        protected DotNetNuke.Web.UI.WebControls.DnnGrid grdUserRoles
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _grdUserRoles;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_grdUserRoles != null)
                {
                    _grdUserRoles.NeedDataSource -= grdUserRoles_NeedDataSource;
                    _grdUserRoles.ItemDataBound -= grdUserRoles_ItemDataBound;
                }

                _grdUserRoles = value;
                if (_grdUserRoles != null)
                {
                    _grdUserRoles.NeedDataSource += grdUserRoles_NeedDataSource;
                    _grdUserRoles.ItemDataBound += grdUserRoles_ItemDataBound;
                }
            }
        }

        /// <summary>
        /// pnlRoleChange_Step2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlRoleChange_Step2;

        /// <summary>
        /// txtNotifyRoleSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnTextBox txtNotifyRoleSubject;

        /// <summary>
        /// txtNotifyRoleBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnEditor txtNotifyRoleBody;

        /// <summary>
        /// btnNotifyRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnNotifyRole;

        protected Button btnNotifyRole
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnNotifyRole;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnNotifyRole != null)
                {
                    _btnNotifyRole.Click -= btnNotifyRole_Click;
                }

                _btnNotifyRole = value;
                if (_btnNotifyRole != null)
                {
                    _btnNotifyRole.Click += btnNotifyRole_Click;
                }
            }
        }

        /// <summary>
        /// btnNotifyRoleSkip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnNotifyRoleSkip;

        protected Button btnNotifyRoleSkip
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnNotifyRoleSkip;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnNotifyRoleSkip != null)
                {
                    _btnNotifyRoleSkip.Click -= btnNotifyRoleSkip_Click;
                }

                _btnNotifyRoleSkip = value;
                if (_btnNotifyRoleSkip != null)
                {
                    _btnNotifyRoleSkip.Click += btnNotifyRoleSkip_Click;
                }
            }
        }

        /// <summary>
        /// pnlEmailTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlEmailTab;

        /// <summary>
        /// lblEmailNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblEmailNote;

        /// <summary>
        /// txtNotifyUserSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnTextBox txtNotifyUserSubject;

        /// <summary>
        /// txtNotifyUserBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnEditor txtNotifyUserBody;

        /// <summary>
        /// btnNotifyUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnNotifyUser;

        protected Button btnNotifyUser
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnNotifyUser;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnNotifyUser != null)
                {
                    _btnNotifyUser.Click -= btnNotifyUser_Click;
                }

                _btnNotifyUser = value;
                if (_btnNotifyUser != null)
                {
                    _btnNotifyUser.Click += btnNotifyUser_Click;
                }
            }
        }

        /// <summary>
        /// pnlMessageTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlMessageTab;

        /// <summary>
        /// lblMessageNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblMessageNote;

        /// <summary>
        /// lblMessageSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblMessageSubject;

        /// <summary>
        /// txtMessageSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtMessageSubject;

        /// <summary>
        /// lblMessageBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblMessageBody;

        /// <summary>
        /// txtMessageBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private TextBox txtMessageBody;

        /// <summary>
        /// btnSendMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnSendMessage;

        protected Button btnSendMessage
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnSendMessage;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnSendMessage != null)
                {
                    _btnSendMessage.Click -= btnSendMessage_Click;
                }

                _btnSendMessage = value;
                if (_btnSendMessage != null)
                {
                    _btnSendMessage.Click += btnSendMessage_Click;
                }
            }
        }

        /// <summary>
        /// pnlSitesTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlSitesTab;

        /// <summary>
        /// lblSitesNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblSitesNote;

        /// <summary>
        /// chkUserSites control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private CheckBoxList chkUserSites;

        /// <summary>
        /// cmdUpdateSites control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdUpdateSites;

        protected LinkButton cmdUpdateSites
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdUpdateSites;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdUpdateSites != null)
                {
                    _cmdUpdateSites.Click -= cmdUpdateSites_Click;
                }

                _cmdUpdateSites = value;
                if (_cmdUpdateSites != null)
                {
                    _cmdUpdateSites.Click += cmdUpdateSites_Click;
                }
            }
        }

        /// <summary>
        /// plhAdditonalControls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private PlaceHolder plhAdditonalControls;

        /// <summary>
        /// pnlCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlCreate;

        /// <summary>
        /// lblCreateAccountNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblCreateAccountNote;

        /// <summary>
        /// plhCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private PlaceHolder plhCreate;

        /// <summary>
        /// cmdAddAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdAddAccount;

        protected LinkButton cmdAddAccount
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdAddAccount;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdAddAccount != null)
                {
                    _cmdAddAccount.Click -= cmdAddAccount_Click;
                }

                _cmdAddAccount = value;
                if (_cmdAddAccount != null)
                {
                    _cmdAddAccount.Click += cmdAddAccount_Click;
                }
            }
        }

        /// <summary>
        /// cmdCancelCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private LinkButton _cmdCancelCreate;

        protected LinkButton cmdCancelCreate
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _cmdCancelCreate;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_cmdCancelCreate != null)
                {
                    _cmdCancelCreate.Click -= cmdCancelCreate_Click;
                }

                _cmdCancelCreate = value;
                if (_cmdCancelCreate != null)
                {
                    _cmdCancelCreate.Click += cmdCancelCreate_Click;
                }
            }
        }

        /// <summary>
        /// pnlRoleMessaging control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Panel pnlRoleMessaging;

        /// <summary>
        /// lblMessagingNotes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Literal lblMessagingNotes;

        /// <summary>
        /// rblMessagingMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private RadioButtonList rblMessagingMode;

        /// <summary>
        /// lblMessagesSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblMessagesSubject;

        /// <summary>
        /// txtEmailSubjectAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnTextBox txtEmailSubjectAll;

        /// <summary>
        /// lblMessagesBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Label lblMessagesBody;

        /// <summary>
        /// txtEmailBodyAll control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private DotNetNuke.Web.UI.WebControls.DnnEditor txtEmailBodyAll;

        /// <summary>
        /// btnSendMessages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnSendMessages;

        protected Button btnSendMessages
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnSendMessages;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnSendMessages != null)
                {
                    _btnSendMessages.Click -= btnSendMessages_Click;
                }

                _btnSendMessages = value;
                if (_btnSendMessages != null)
                {
                    _btnSendMessages.Click += btnSendMessages_Click;
                }
            }
        }

        /// <summary>
        /// btnCancelMessaging control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        private Button _btnCancelMessaging;

        protected Button btnCancelMessaging
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnCancelMessaging;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnCancelMessaging != null)
                {
                    _btnCancelMessaging.Click -= btnCancelMessaging_Click;
                }

                _btnCancelMessaging = value;
                if (_btnCancelMessaging != null)
                {
                    _btnCancelMessaging.Click += btnCancelMessaging_Click;
                }
            }
        }
    }
}